### ISSUE TITLE
error when testing the installation of pyqz

### ISSUE THREAD

**Issue by ami88** [fpavogt/pyqz#2]
Hello again,

I am trying to reproduce the section "More tests with unittest" in the installation. In the version of pyqz that I have installed the file within 'unittest' is called pyqz_checks.py, not pyqz_check.py so I type:
In [27]: run pyqz_checks.py
and I get many errors (I will copy the messages on the screen at the end). Apparently, I have all the needed requirements:

Package and versions:
numpy: '1.12.0'
scipy: '0.18.1'
matplotlib: '2.0.0'
statsmodels: '0.8.0'

Any idea of what is going wrong?

Best regards,

Ana

P.S. I will post another issue in short. I don't know if it is related with this one or not, so I prefer to put it in another ticket.

========================================
 Starting pyqz tests:

test01_interpgridnodes (__main__.Testpyqz) ... ok
test02_interpoffgrid (__main__.Testpyqz) ... ERROR
test03_interp_midMVq (__main__.Testpyqz) ...  
--> Received 1 spectrum ...
--> Dealing with them one at a time ... be patient now !
    (no status update until I am done ...)
ERROR
test04_get_bad_global_qz (__main__.Testpyqz) ...  
--> Received 1 spectrum ...
--> Dealing with them one at a time ... be patient now !
    (no status update until I am done ...)
ERROR
test05_multiprocessing (__main__.Testpyqz) ...  
--> Received 1 spectrum ...
--> Launching the multiple processes ... 
ERROR.. 1 job(s) left ...
test06_speed_benchmark (__main__.Testpyqz) ...  
--> Received 1 spectrum ...
--> Dealing with them one at a time ... be patient now !
    (no status update until I am done ...)
ERROR
test07_plots (__main__.Testpyqz) ... ok

======================================================================
ERROR: test02_interpoffgrid (__main__.Testpyqz)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ami/Codigos/pyqz-0.8.0/unittest/pyqz_checks.py", line 211, in test02_interpoffgrid
    out = interpoffgrid()
  File "/Users/ami/Codigos/pyqz-0.8.0/unittest/pyqz_checks.py", line 72, in interpoffgrid
    sampling = sampling)
  File "/Users/ami/Codigos/pyqz-0.8.0/src/pyqz.py", line 291, in interp_qz
    data[i] = data[i].reshape(input_data_size)
TypeError: 'numpy.float64' object cannot be interpreted as an index

======================================================================
ERROR: test03_interp_midMVq (__main__.Testpyqz)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ami/Codigos/pyqz-0.8.0/unittest/pyqz_checks.py", line 217, in test03_interp_midMVq
    out = interp_midMVq(nproc = 1, KDE_pickle_loc = './plots')
  File "/Users/ami/Codigos/pyqz-0.8.0/unittest/pyqz_checks.py", line 134, in interp_midMVq
    verbose = True)
  File "/Users/ami/Codigos/pyqz-0.8.0/src/pyqz.py", line 1177, in get_global_qz
    results = map(get_global_qz_singlespec, jobs)
  File "/Users/ami/Codigos/pyqz-0.8.0/src/pyqz.py", line 906, in get_global_qz_singlespec
    mean_qz = stats.stats.nanmean(final_data[np.array(which_qz[qz])])
AttributeError: 'module' object has no attribute 'nanmean'

======================================================================
ERROR: test04_get_bad_global_qz (__main__.Testpyqz)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ami/Codigos/pyqz-0.8.0/unittest/pyqz_checks.py", line 223, in test04_get_bad_global_qz
    out = get_bad_global_qz()
  File "/Users/ami/Codigos/pyqz-0.8.0/unittest/pyqz_checks.py", line 196, in get_bad_global_qz
    verbose = True)
  File "/Users/ami/Codigos/pyqz-0.8.0/src/pyqz.py", line 1177, in get_global_qz
    results = map(get_global_qz_singlespec, jobs)
  File "/Users/ami/Codigos/pyqz-0.8.0/src/pyqz.py", line 710, in get_global_qz_singlespec
    gridymin:gridymax]
TypeError: slice indices must be integers or None or have an __index__ method

=======================================================================
ERROR: test05_multiprocessing (__main__.Testpyqz)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ami/Codigos/pyqz-0.8.0/unittest/pyqz_checks.py", line 229, in test05_multiprocessing
    out = interp_midMVq(nproc=2, KDE_pickle_loc = './plots')
  File "/Users/ami/Codigos/pyqz-0.8.0/unittest/pyqz_checks.py", line 134, in interp_midMVq
    verbose = True)
  File "/Users/ami/Codigos/pyqz-0.8.0/src/pyqz.py", line 1208, in get_global_qz
    sys.stdout.write("    %i job(s) completed.      \n" % len(results))
TypeError: object of type 'exceptions.AttributeError' has no len()

======================================================================
ERROR: test06_speed_benchmark (__main__.Testpyqz)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ami/Codigos/pyqz-0.8.0/unittest/pyqz_checks.py", line 243, in tt06_speed_benchmark 
    sampling=1,KDE_qz_sampling=101j, do_single_spec = True)
  File "/Users/ami/Codigos/pyqz-0.8.0/unittest/pyqz_checks.py", line 134, in interp_midMVq
    verbose = True)
  File "/Users/ami/Codigos/pyqz-0.8.0/src/pyqz.py", line 1177, in get_global_qz
    results = map(get_global_qz_singlespec, jobs)
  File "/Users/ami/Codigos/pyqz-0.8.0/src/pyqz.py", line 906, in get_global_qz_singlespec
    mean_qz = stats.stats.nanmean(final_data[np.array(which_qz[qz])])
AttributeError: 'module' object has no attribute 'nanmean'

----------------------------------------------------------------------
Ran 7 tests in 43.344s

FAILED (errors=5)

**Comment by fpavogt** [comment]
Same thing here, this is all related to numpy 1.12 as far as I can tell.

**Comment by fpavogt** [comment]
Fixed with latest commit.
